[env]
MYRIAD_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
python = { version = '3.13.4' }
node = { version = 'lts' }
bun = { version = '1.2.15' }
go = { version = '1.24.4' }
'gem:neocities' = { version = '0.0.20' }

[tasks]
'hello' = { run = "echo 'Hello, world!'" }
'netflow:up' = { run = "docker compose -f code/docker/netflow/docker-compose.template.yml up" }
'netflow:down' = { run = "docker compose -f code/docker/netflow/docker-compose.template.yml down" }
'netflow:logs' = { run = "docker compose -f code/docker/netflow/docker-compose.template.yml logs -f" }
'netflow:rm' = { run = "docker compose -f code/docker/netflow/docker-compose.template.yml rm" }
