name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  MISE_EXPERIMENTAL: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: apt
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev node-gyp pkg-config python-is-python3 google-chrome-stable
      - name: checkout
        uses: actions/checkout@v4
      - name: mise
        uses: jdx/mise-action@v2
      - name: prepare-ci
        run: bin/mise run prepare-ci
      - name: ci:brakeman
        run: bin/mise run ci:brakeman
      - name: ci:rubocop
        run: bin/mise run ci:rubocop
      # - name: ci:test
      #   run: bin/mise run ci:test
      - name: artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
