services:
  ntopng:
    image: ghcr.io/daveio/netflow:latest
    # Or build from local Dockerfile:
    # build: ./components
    container_name: ntopng
    # environment:
      # Optional: Use remote Redis instead of local
      # - REMOTE_REDIS=redis.example.com:6379
    ports:
      - 8849:8849     # ntopng web interface
      - 2055:2055/udp # NetFlow/sFlow/IPFIX collector
    volumes:
      - netflow-data:/var/lib/ntopng
      - netflow-logs:/var/log/ntopng
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8849/lua/rest/v2/get/system/stats.lua
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  netflow-data:
    driver: local
  netflow-logs:
    driver: local
