services:
  ntopng:
    image: ghcr.io/daveio/netflow:latest
    container_name: ntopng
    environment:
      - GEOIPUPDATE_DB_DIR=/var/lib/GeoIP
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country GeoLite2-City GeoLite2-ASN
      - GEOIPUPDATE_VERBOSE=1
      - GEOIPUPDATE_ACCOUNT_ID=xxxGEOIPUPDATE_ACCOUNT_IDxxx
      - GEOIPUPDATE_LICENSE_KEY=xxxGEOIPUPDATE_LICENSE_KEYxxx
    command: >
      sh -c "
      # Install geoipupdate if not present
      if ! command -v geoipupdate >/dev/null 2>&1; then
        apk add --no-cache geoipupdate || apt-get update && apt-get install -y geoipupdate || yum install -y geoipupdate
      fi &&
      # Create GeoIP directory
      mkdir -p /var/lib/GeoIP &&
      # Update GeoIP databases
      geoipupdate -v &&
      # Start ntopng with netflow support
      ntopng -P /var/lib/ntopng.pid
      -d /var/lib/ntopng
      -w 3000
      -i tcp://0.0.0.0:2055
      --zmq tcp://*:5556
      --http-prefix /
      --dont-change-user
      --verbose 2
      --interface-name netflow
      --community
      "
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 60s
      test:
        - CMD-SHELL
        - curl -f http://localhost:3000 || exit 1
      timeout: 10s
    network_mode: bridge
    ports:
      - 8849:8849/tcp # Web interface
      - 2055:2055/udp # NetFlow collector
    restart: unless-stopped
    volumes:
      - ntop-lib:/var/lib/ntopng
      - ntop-log:/var/log/ntopng
      - ntop-run:/var/run
      - /etc/localtime:/etc/localtime:ro

volumes:
  ntop-lib:
    driver: local
  ntop-log:
    driver: local
  ntop-run:
    driver: local
