action_id: trunk-upgrade-available
date: 2024-11-07 21:21:28
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1731014488
full_timestamp:
  nanos: 441186000
  seconds: 1731014488
trunk_version: 1.22.8
