services:
  netflow2ng:
    security_opt:
      - no-new-privileges:true
    read_only: true
    image: synfinatic/netflow2ng:latest
    container_name: netflow2ng
    entrypoint: /netflow2ng # --level=debug
    environment:
      - TZ=Europe/London # Example: Set to your local timezone, e.g., America/New_York
    command:
      - -listen-udp=:2055
      - -zmq-uri=tcp://0.0.0.0:5556
    ports:
      - 5556:5556/tcp
      - 8080:8080/tcp
      - 2055:2055/udp
    networks:
      - monitoring_net
    restart: unless-stopped
  ntopng:
    security_opt:
      - no-new-privileges:true
    read_only: true
    image: ntop/ntopng:stable
    container_name: ntopng
    command:
      - -i
      - tcp://netflow2ng:5556
      - --community
      - -m
      - 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8 # Adjust to your local network(s)
    ports:
      - 3000:3000
    volumes:
      - ntopng-data:/var/lib/ntopng # Using a named volume
      # Alternatively, use a bind mount:
      # - ./ntopng_data:/var/lib/ntopng
    networks:
      - monitoring_net
    depends_on:
      - netflow2ng
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Example: Set to your local timezone, e.g., America/New_York
networks:
  monitoring_net:
    driver: bridge
volumes:
  ntopng-data: # Definition for the named volume
