services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - ntopng
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - ntopng
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ntopng
    networks:
      - ntopng
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ntopng
    depends_on:
      - elasticsearch
  netflow2ng:
    image: synfinatic/netflow2ng:latest
    restart: unless-stopped
    command:
      [
        --zmq-output=tcp://ntopng:5556,
        --netflow-port=2055,
        --metrics-addr=:9100,
        --log-level=info,
      ]
    ports:
      # This will bind to both IPv4 and IPv6
      - 2055:2055/udp
      - 9100:9100
    networks:
      - ntopng
    depends_on:
      - ntopng
  ntopng:
    networks:
      - ntopng
    image: ntop/ntopng:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - ntopng:/var/lib/ntopng
      - ./ntopng.conf:/etc/ntopng/ntopng.conf:ro
    environment:
      - REDIS_SERVER=redis
    command: [
        --community,
        -i,
        tcp://127.0.0.1:5556,
        -r,
        redis,
        --http-port,
        "3000", # Binds to all interfaces including IPv6
      ]
    depends_on:
      - redis
      - influxdb
      - elasticsearch
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - ntopng
volumes:
  elasticsearch:
  grafana:
  influxdb:
  ntopng:
  redis:
networks:
  ntopng:
    driver: bridge
    enable_ipv6: true # Enable IPv6 on the bridge network
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8:1::/64 # IPv6 subnet
