version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: ntopng-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ntopng-network
  netflow2ng:
    image: synfinatic/netflow2ng:latest
    container_name: netflow2ng
    restart: unless-stopped
    command:
      [
        --zmq-output=tcp://ntopng:5556,
        --netflow-port=2055,
        --metrics-addr=:9100,
        --log-level=info,
      ]
    ports:
      # This will bind to both IPv4 and IPv6
      - 2055:2055/udp
      - 9100:9100
    networks:
      - ntopng-network
    depends_on:
      - ntopng
  ntopng:
    image: ntop/ntopng:stable
    container_name: ntopng
    restart: unless-stopped
    network_mode: host
    volumes:
      - ntopng_data:/var/lib/ntopng
      - ./ntopng.conf:/etc/ntopng/ntopng.conf:ro
    environment:
      - REDIS_SERVER=redis
    command: [
        --community,
        -i,
        tcp://127.0.0.1:5556,
        -r,
        redis,
        --http-port,
        3000, # Binds to all interfaces including IPv6
      ]
    depends_on:
      - redis
volumes:
  ntopng_data:
  redis_data:
networks:
  ntopng-network:
    driver: bridge
    enable_ipv6: true # Enable IPv6 on the bridge network
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8:1::/64 # IPv6 subnet
