services:
  netflow2ng:
    container_name: netflow2ng
    restart: unless-stopped
    image: synfinatic/netflow2ng@sha256:d3a91dee9f2dd99f5b9bad48d3de5409e19cf0f61a571cf7dc1460cbe0937885
    entrypoint: /netflow2ng
    command:
      - --metrics=:9101
      - --log-level=info
    network_mode: host
    depends_on:
      - ntopng
  ntopng:
    container_name: ntopng
    user: root
    command:
      - -G /var/lib/ntopng/ntopng.pid
      - -i eth1.1
      - --community
      - --disable-autologout
      - --disable-login=1  # Living dangerously! Add authentication in production
      - -m 10.0.98.0/24
      - -m 10.0.99.0/24
      - --redis=localhost:8846
      - --http-port=8849
      - --max-num-flows=200000
      - --max-num-hosts=100000
    image: >-
      ntop/ntopng@sha256:7121cca717ab921e414781805f8e9295ca70bf3a5268cfeaac55822549066d0b
    network_mode: host
    restart: unless-stopped
    volumes:
      - ntopng:/var/lib/ntopng
volumes:
  ntopng: null
