services:
  ntopng:
    build: .
    container_name: ntopng-netflow
    ports:
      - 3000:3000      # ntopng web interface
      - 2055:2055/udp  # netflow input
      - 8080:8080      # http input for netflow
    volumes:
      - ntopng_data:/var/lib/ntopng
      - ntopng_logs:/var/log/ntopng
    environment:
      # GEOIPUPDATE_ACCOUNT_ID: "your_account_id_here"
      # GEOIPUPDATE_LICENSE_KEY: "your_license_key_here"
      # REMOTE_REDIS: "redis.example.com:6379"  # or just "redis.example.com" (defaults to port 6379)
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-City GeoLite2-ASN
      GEOIPUPDATE_DB_DIR: /usr/share/GeoIP
      GEOIPUPDATE_VERBOSE: "1"
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3000/lua/rest/v2/get/system/stats.lua
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  ntopng_data:
    driver: local
  ntopng_logs:
    driver: local
