services:
  elasticsearch:
    # 8.13.1
    image: docker.elastic.co/elasticsearch/elasticsearch@sha256:8b6d74cc54efff126b8646697ab4be0116959d9c7fb29b0a40605e0e9518df2a
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - ntopng
  grafana:
    # 10.3.3
    image: grafana/grafana@sha256:8640e5038e83ca4554ed56b9d76375158bcd51580238c6f5d8adaf3f20dd5379
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - ntopng
    depends_on:
      - influxdb
  influxdb:
    # 2.7.5
    image: influxdb@sha256:766904dcef641fa1491750b7b3e0dd948b30417f7ef0ac4d3f1d6ffed52a1fa2
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ntopng
    networks:
      - ntopng
  kibana:
    # 8.13.1
    image: docker.elastic.co/kibana/kibana@sha256:0a002f6121aeaecb02c1c9b0b19580d26d47013620653e06fc3f661cea39134e
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ntopng
    depends_on:
      - elasticsearch
  netflow2ng:
    # v0.0.5
    image: synfinatic/netflow2ng@sha256:d3a91dee9f2dd99f5b9bad48d3de5409e19cf0f61a571cf7dc1460cbe0937885
    restart: unless-stopped
    command:
      [
        --zmq-output=tcp://ntopng:5556,
        --netflow-port=2055,
        --metrics-addr=:9100,
        --log-level=info,
      ]
    ports:
      # This will bind to both IPv4 and IPv6
      - 2055:2055/udp
      - 9100:9100
    networks:
      - ntopng
    depends_on:
      - ntopng
  ntopng:
    networks:
      - ntopng
    # latest
    image: ntop/ntopng@sha256:7121cca717ab921e414781805f8e9295ca70bf3a5268cfeaac55822549066d0b
    restart: unless-stopped
    network_mode: host
    volumes:
      - ntopng:/var/lib/ntopng
      - ./ntopng.conf:/etc/ntopng/ntopng.conf:ro
    environment:
      - REDIS_SERVER=redis
    command: [
        --community,
        -i,
        tcp://127.0.0.1:5556,
        -r,
        redis,
        --http-port,
        "3000", # Binds to all interfaces including IPv6
      ]
    depends_on:
      - redis
      - influxdb
      - elasticsearch
  redis:
    # 7.2.4-alpine
    image: redis@sha256:c8bb255c3559b3e458766db810aa7b3c7af1235b204cfdb304e79ff388fe1a5a
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - ntopng
volumes:
  elasticsearch:
  grafana:
  influxdb:
  ntopng:
  redis:
networks:
  ntopng:
    driver: bridge
    enable_ipv6: true # Enable IPv6 on the bridge network
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8:1::/64 # IPv6 subnet
