services:
  ntopng:
    build: .
    env_file:
      - .env
    environment:
      GEOIPUPDATE_DB_DIR: /usr/share/GeoIP
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-City GeoLite2-ASN
      GEOIPUPDATE_VERBOSE: 1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8849/lua/rest/v2/get/system/stats.lua
      timeout: 10s
    network_mode: host # 8849/tcp, 2055/udp
    restart: unless-stopped
    volumes:
      - ntop-lib:/var/lib/ntopng
      - ntop-log:/var/log/ntopng
      - ntop-run:/var/run/ntopng
volumes:
  ntop-lib:
    driver: local
  ntop-log:
    driver: local
  ntop-run:
    driver: local
