name: netflow
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netflow
jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.metadata.outputs.tags }}
      digest: ${{ steps.push.outputs.digest }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: buildx
        id: buildx
        uses: docker/setup-buildx-action@3f1544eb9eff0b4d4d279b33f704a06fcf8d0e43
      - name: login
        id: login
        uses: docker/login-action@6d4b68b490aef8836e8fb5e50ee7b3bdfa5894f0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: metadata
        id: metadata
        run: |
          {
            echo "tags=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
            echo "labels=org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}"
            echo "labels=org.opencontainers.image.revision=${{ github.sha }}"
          } >> "$GITHUB_OUTPUT"
      - name: push
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./projects/netflow/components
          file: ./projects/netflow/components/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
      - name: image
        id: image
        run: |
          echo "Image pushed to: ${{ steps.metadata.outputs.tags }}"
          echo "Short SHA: ${{ github.sha }}"
          echo "Full image reference: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "Image digest: ${{ steps.push.outputs.digest }}"
  slsa:
    needs:
      - push
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.9.0
    with:
      image: ${{ needs.push.outputs.image }}
      digest: ${{ needs.push.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
